//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class EPostalar
    {
        public int Id { get; set; }
        public string AdSoyad { get; set; }
        public string Eposta { get; set; }
        public string Konu { get; set; }
        public string Telefon { get; set; }
        public string Mesaj { get; set; }
        public Nullable<int> SiteId { get; set; }
        public Nullable<System.DateTime> EmailTarih { get; set; }
    
        public virtual Site Site { get; set; }
    }
}
