//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Icerikler
    {
        public int Id { get; set; }
        public Nullable<int> SayfaId { get; set; }
        public string Baslik { get; set; }
        public string Text { get; set; }
        public string AltBaslik { get; set; }
        public string AltBaslikText { get; set; }
        public string Resim1 { get; set; }
        public string Resim2 { get; set; }
        public string Resim3 { get; set; }
        public string Resim4 { get; set; }
        public bool IsActive { get; set; }
        public bool IsDelete { get; set; }
        public Nullable<int> Sıra { get; set; }
        public string Video1 { get; set; }
        public string Video2 { get; set; }
        public string Video3 { get; set; }
        public string Dil { get; set; }
        public Nullable<int> SiteId { get; set; }
    
        public virtual Sayfalar Sayfalar { get; set; }
        public virtual Site Site { get; set; }
    }
}
