//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sayfalar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sayfalar()
        {
            this.Icerikler = new HashSet<Icerikler>();
        }
    
        public int Id { get; set; }
        public string SayfaAdi { get; set; }
        public Nullable<int> SiteId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Icerikler> Icerikler { get; set; }
        public virtual Site Site { get; set; }
    }
}
