//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Siparis
    {
        public int Id { get; set; }
        public string SiparisTarih { get; set; }
        public string AdSoyad { get; set; }
        public string EPosta { get; set; }
        public Nullable<int> UrunId { get; set; }
        public string Adet { get; set; }
        public string Adres { get; set; }
        public string Telefon { get; set; }
        public bool IsActive { get; set; }
        public bool IsDelete { get; set; }
        public int SehirId { get; set; }
        public string Aciklama { get; set; }
        public Nullable<int> SiparisDurum { get; set; }
        public Nullable<int> SiteId { get; set; }
    
        public virtual Sehirler Sehirler { get; set; }
        public virtual Site Site { get; set; }
        public virtual Urun Urun { get; set; }
    }
}
