//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class UrunDetay
    {
        public int Id { get; set; }
        public string UrunAdi { get; set; }
        public Nullable<int> UrunStok { get; set; }
        public string UrunAciklama { get; set; }
        public int UrunId { get; set; }
        public string UrunResim { get; set; }
    
        public virtual Urun Urun { get; set; }
    }
}
